config/routes.rb
Rails.application.routes.draw do
  # devise_for :views
  devise_for :users
  root "users#index"
  get 'users/show'
  resources :users, only: [:index, :show] do
    resources :posts do
      resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create]    
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  belongs_to :post, foreign_key: :post_id

  after_save :update_comment_counter

  def update_comment_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  belongs_to :post, foreign_key: :post_id

  after_save :update_post_likes_count

  def update_post_likes_count
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :likes, counter_cache: true
  has_many :comments, foreign_key: :post_id

  after_save :update_posts_counter
  validates :title, presence: true
  validates :title, length: { maximum: 250, too_long: 'Name must not exceed 250 characters' }
  validates_numericality_of :comments_counter, greater_than_or_equal_to: 0, message:
    'Comments counter must be an integer greater than or eaqual to zero'
  validates_numericality_of :likes_counter, greater_than_or_equal_to: 0, message:
    'Likes counter must be an integer greater than or equal to zero'

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_posts_counter
    author.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id

  validates :name, presence: true, allow_blank: false
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.order('created_at DESC').first(3)
  end
end

app/models/view.rb
class View < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery prepend: true
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  private

  def after_sign_out_path_for(_resource_or_scope)
    new_user_session_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password password_confirmation])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.author = current_user
    @comment.post = @post

    if @comment.save
      redirect_to user_post_path(@user, @post)
    else
      render 'posts/show'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @like = Like.new
    @like.author = current_user
    @like.post = @post

    if @like.save
      redirect_to user_post_path(@user, @post)
    else
      render 'posts/show'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
  end

  def show
    @post = Post.includes(:comments, :likes).find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      flash[:notice] = 'Post saved successfully'
      redirect_to user_post_path(current_user, @post)
    else
      flash.now[:error] = 'Post could not be created!!'
      render :new
    end
  end

  private

  # # private method which will be used to filter the parameters that are passed to the create method.
  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_with model: Comment, url: user_post_comments_path(@post.author, @post) do |form| %>
    <div>
        <%= form.label 'Add Comment' %> <br/><br/>
        <%= form.text_area :text, placeholder: 'Add Comment', row: 20, required: true %> <br/>
    </div>
    <div>
        <%= form.submit 'Add Comment' %>
    </div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class='container mt-4'>
  <%= render 'navbar/header' %>
  <p class = "notice"><%= notice %></p>
  <p class = "alert"><%= alert %></p>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

app/views/likes/_like.html.erb
<section>
    <%= form_with model: Like, url: user_post_likes_path(@post.author, @post) do |form| %>
    <%= form.submit 'Like' %>
    <% end %>
</section>

app/views/navbar/_header.html.erb
<nav class="navbar navbar-expand-lg bg-dark">
  <div class="container-fluid">

  <%= link_to 'Home', root_path, class: "navbar-brand text-white" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link text-white" href="#"></a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      
<div class="nav">
    <%if user_signed_in? %>
      <%= button_to "Sign Out", destroy_user_session_path, method: :delete %>
    <% else %>
    <ul class="navbar-nav me-auto mb-4 mb-lg-0">
      <%= link_to "Sign In", new_user_session_path %>
      </ul>
      <ul>
       <li><%= render "devise/shared/links" %></li>
       </ul>
    <% end %>
  </div>
    </div>
  </div>
</nav>

app/views/posts/_form.html.erb
<div class="container">
  <h2>New Post</h2>
  <%= form_with model: Post, url: user_posts_path do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title %>
      <%= f.label :text %>
      <%= f.text_area :text %>
      <%= f.submit "Create a Post" %>
  <% end %>
</div>

app/views/posts/index.html.erb
<section>
  <div class='single-user'>
    <div class='user-photo'>
      <img src='<%= @user.photo %>' alt='<%= @user.name %> thumbnail' />
    </div>
    <div class='user-name'>
      <h2><%= @user.name %></h2>
      <p>Number of Posts: <%= @user.posts_counter %></p>
    </div>
  </div>
  <div class='user-posts'>
  <% @user.posts.each do |post| %>
    <div class='list-posts'>
    <h5><%= link_to post.title, user_post_path(@user, post) %></h5>
    <p><%= post.text %></p>
    <span class='like-comment'>
    Comments: <%= post.comments_counter || 0 %>, 
    Likes: <%= post.likes_counter || 0 %> 
    </span>
    </div>
    <ul class='post-comment'>
    <% if post.recent_comments.length == 0 %>
    <p>No comments added!</p>
    <% else %>
    <% post.recent_comments.each do |comment| %>
      <li><%= comment.author.name %>: <%= comment.text %></li>
      <% end %>
      <% end %>
      </ul>
      <% end %>
      </div>
  <h4><%= link_to 'Add new Post', new_user_post_path %></h4>
</section>

app/views/posts/new.html.erb
<section class="container">

    <p class="post-title">Create a new Post:</p>
    <%= form_with model: Post, url: user_posts_url, class: "form" do |f|  %>
   <%= f.text_field :title, placeholder:"Title", id:"post_title", autofocus: true %>
  
  <div>
   <%= f.text_area :text, placeholder:"Write your content...", id:"post_text"%>
  </div>
  <div id="buttons_div">
   <%= f.submit "Save your post" %>
  </div>
<% end %>
</section>

app/views/posts/show.html.erb
<section>
    <div class = 'listed-posts'>
        <h4><%= @post.title%> by <%= @post.author.name%></h4>
        <p><%= @post.text  %></p>
        <span class = 'comment-likes'>
            Comments: <%= @post.comments_counter || 0 %>
            <%= render 'comments/form' %>
            Likes: <%= @post.likes_counter || 0 %>
            <%= render 'likes/like' %>            
    </div>
    <ul class = 'comments-info'>
        <% if @post.comments.length == 0 %>
            <p>No comments yet</p>
        <% else %>
            <% @post.comments.each do |comment| %>
                <li><%= comment.author.name %> : <%= comment.text %></li>
            <%end%>
        <%end%>
    </ul>
</section>

app/views/users/index.html.erb
<section>
    <ul class = 'user-style-home'>
        <% @users.each do |user| %>
            <li>
                <div class = 'users-photo'>
                    <img src='<%= user.photo %>' alt = '<%= user.name %> photo' />
                </div>
                <div class = 'user-detail'>
                    <h2><%= link_to user.name, user_path(user) %></h2>
                    <p>Number of posts: <%= user.posts_counter %></p>
                </div>
            </li>
        <%end%>
    </ul>
</section>

app/views/users/show.html.erb
<section>
<div class = 'user-info'>
    <div class = 'user-photo'>
        <img src='<%= @user.photo %>' alt = '<%= @user.name %> photo' />
    </div>
    <div class = 'user-detail'>
        <h2> <%= @user.name %></h2>
        <p>Number of posts: <%= @user.posts_counter %></p>
    </div>
</div>
<div class = 'bio'>
    <h3>Bio</h3>
    <p><%= @user.bio %></p>
</div>

<div class = 'posts'>
    <% @user.three_recent_posts.each do |post| %>
        <div class = 'myposts'>
            <h4><%= link_to post.title, user_post_path(@user, post)  %></h4>
            <p><%= post.text %></p>
            <span class = 'comments-likes'>
                Comments: <%= post.comments_counter || 0 %>
                Likes: <%= post.likes_counter || 0 %>
            </span>
        </div>
    <% end %>
</div>
<button class = 'view-all-posts'>
    <%= link_to 'see all posts', user_posts_path(@user) %>
</button>
</section>